const escola = "Unisinos"
console.log(escola.charAt(4))
console.log(escola.charAt(10))
console.log(escola.charCodeAt(2))
console.log(escola.indexOf("a"))
console.log(escola.substring(1))
console.log(escola.substring(0, 3))
console.log(escola.concat(" Ramos"))
console.log(escola.replace(/\w/g, 'x'))
console.log(escola.replace("a", 'x'))
console.log(escola.split("s"))
console.log(escola + "teste")